-- DFG Orchestrator Schema v1
-- Phase 0: Manual dispatch, comments only, full audit trail
-- 
-- Design principles:
-- 1. Immutable audit logs with full provenance
-- 2. Circuit breaker state persisted (not in-memory)
-- 3. De-dupe via content hash
-- 4. Generate → Policy → Act separation

-- ============================================================================
-- ORCHESTRATOR RUNS
-- One row per dispatch invocation
-- ============================================================================
CREATE TABLE IF NOT EXISTS orchestrator_runs (
  id TEXT PRIMARY KEY,
  trigger_type TEXT NOT NULL CHECK (trigger_type IN ('manual', 'cron', 'webhook')),
  phase TEXT NOT NULL DEFAULT 'phase0',
  started_at TEXT NOT NULL,
  completed_at TEXT,
  
  -- Task tracking
  tasks_dispatched INTEGER NOT NULL DEFAULT 0,
  tasks_succeeded INTEGER NOT NULL DEFAULT 0,
  tasks_failed INTEGER NOT NULL DEFAULT 0,
  tasks_skipped INTEGER NOT NULL DEFAULT 0,
  
  -- Cost tracking
  total_input_tokens INTEGER NOT NULL DEFAULT 0,
  total_output_tokens INTEGER NOT NULL DEFAULT 0,
  estimated_cost_usd REAL NOT NULL DEFAULT 0,
  
  -- Circuit breaker state
  stopped_early INTEGER NOT NULL DEFAULT 0,
  stop_reason TEXT,
  
  -- Error tracking
  error_message TEXT,
  error_stack TEXT
);

CREATE INDEX idx_runs_started ON orchestrator_runs(started_at DESC);
CREATE INDEX idx_runs_trigger ON orchestrator_runs(trigger_type);

-- ============================================================================
-- TASK RESULTS
-- One row per Claude API call
-- ============================================================================
CREATE TABLE IF NOT EXISTS task_results (
  id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL REFERENCES orchestrator_runs(id),
  
  -- Task identity
  task_type TEXT NOT NULL,
  target_type TEXT NOT NULL CHECK (target_type IN ('issue', 'pr')),
  target_id TEXT NOT NULL,
  target_url TEXT,
  
  -- Provenance (immutable audit trail)
  input_hash TEXT NOT NULL,           -- SHA256 of input payload
  context_hash TEXT NOT NULL,         -- SHA256 of context pack
  context_pack_version TEXT NOT NULL, -- e.g., "2026-01-09"
  model_version TEXT NOT NULL,        -- e.g., "claude-sonnet-4-20250514"
  prompt_version TEXT NOT NULL,       -- Git SHA or version string of prompt template
  prompt_template_hash TEXT,          -- SHA256 of actual prompt text used (Pre-flight fix #1)
  
  -- Source refs
  source_url TEXT,
  source_commit_sha TEXT,
  
  -- Result
  status TEXT NOT NULL CHECK (status IN ('success', 'failed', 'skipped_dedupe', 'skipped_breaker')),
  output_json TEXT,
  error_message TEXT,
  
  -- Retry tracking
  attempt_count INTEGER NOT NULL DEFAULT 1,
  retry_delays_ms TEXT,  -- JSON array of delays between attempts
  
  -- Cost
  input_tokens INTEGER,
  output_tokens INTEGER,
  duration_ms INTEGER,
  
  created_at TEXT NOT NULL
);

CREATE INDEX idx_task_results_dedupe ON task_results(task_type, target_id, input_hash);
CREATE INDEX idx_task_results_run ON task_results(run_id);
CREATE INDEX idx_task_results_created ON task_results(created_at DESC);
CREATE INDEX idx_task_results_status ON task_results(status);

-- ============================================================================
-- PROPOSED ACTIONS
-- Actions generated by Claude, classified by Policy phase
-- ============================================================================
CREATE TABLE IF NOT EXISTS proposed_actions (
  id TEXT PRIMARY KEY,
  task_result_id TEXT NOT NULL REFERENCES task_results(id),
  
  -- Action details
  action_type TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  
  -- Provenance (required by schema)
  reason TEXT NOT NULL,
  evidence TEXT NOT NULL,
  
  -- Policy decision
  classification TEXT NOT NULL CHECK (classification IN ('auto_safe', 'requires_approval', 'rejected')),
  policy_reason TEXT NOT NULL,
  policy_checks_json TEXT,  -- JSON of all policy checks run
  
  -- Execution state
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'executed', 'failed')),
  executed_at TEXT,
  executed_by TEXT,  -- 'auto' | 'captain' | user id
  execution_result_json TEXT,
  execution_error TEXT,
  
  created_at TEXT NOT NULL
);

CREATE INDEX idx_proposed_actions_pending ON proposed_actions(status) WHERE status = 'pending';
CREATE INDEX idx_proposed_actions_task ON proposed_actions(task_result_id);
CREATE INDEX idx_proposed_actions_created ON proposed_actions(created_at DESC);

-- ============================================================================
-- CIRCUIT BREAKER STATE (Pre-flight fix #3)
-- Persisted across Worker invocations
-- ============================================================================
CREATE TABLE IF NOT EXISTS circuit_breaker_state (
  id TEXT PRIMARY KEY DEFAULT 'global',
  window_start TEXT NOT NULL,         -- Start of current tracking window
  window_duration_hours INTEGER NOT NULL DEFAULT 1,
  
  -- Counters (reset when window expires)
  total_tasks INTEGER NOT NULL DEFAULT 0,
  failed_tasks INTEGER NOT NULL DEFAULT 0,
  total_cost_usd REAL NOT NULL DEFAULT 0,
  
  -- Thresholds
  max_tasks_per_window INTEGER NOT NULL DEFAULT 50,
  max_cost_per_window_usd REAL NOT NULL DEFAULT 5.0,
  error_rate_threshold REAL NOT NULL DEFAULT 0.5,
  
  -- State
  is_open INTEGER NOT NULL DEFAULT 0,  -- 1 = breaker tripped, reject all
  opened_at TEXT,
  open_reason TEXT,
  
  updated_at TEXT NOT NULL
);

-- Initialize default circuit breaker state
INSERT OR IGNORE INTO circuit_breaker_state (id, window_start, updated_at)
VALUES ('global', datetime('now'), datetime('now'));

-- ============================================================================
-- PROMPT TEMPLATES (Pre-flight fix #1)
-- Store actual prompt text for reproducibility
-- ============================================================================
CREATE TABLE IF NOT EXISTS prompt_templates (
  id TEXT PRIMARY KEY,  -- SHA256 hash of content
  task_type TEXT NOT NULL,
  version TEXT NOT NULL,
  system_prompt TEXT NOT NULL,
  user_prompt_template TEXT NOT NULL,
  context_pack TEXT NOT NULL,
  
  created_at TEXT NOT NULL,
  
  UNIQUE(task_type, version)
);

CREATE INDEX idx_prompt_templates_task ON prompt_templates(task_type);
